"""
MegaCommerce Domain Enumerations & System Constants
"""

from enum import Enum


class UserRole(str, Enum):
    CUSTOMER = "CUSTOMER"
    SELLER = "SELLER"
    ADMIN = "ADMIN"
    SYSTEM_AUDITOR = "SYSTEM_AUDITOR"
    WAREHOUSE_MANAGER = "WAREHOUSE_MANAGER"
    DELIVERY_AGENT = "DELIVERY_AGENT"


class UserStatus(str, Enum):
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    DEACTIVATED = "DEACTIVATED"


class ProductStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    ARCHIVED = "ARCHIVED"


class OrderStatus(str, Enum):
    CREATED = "CREATED"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    CONFIRMED = "CONFIRMED"
    PROCESSING = "PROCESSING"
    PACKED = "PACKED"
    SHIPPED = "SHIPPED"
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"
    RETURN_REQUESTED = "RETURN_REQUESTED"
    RETURN_APPROVED = "RETURN_APPROVED"
    RETURNED = "RETURNED"
    REFUND_PENDING = "REFUND_PENDING"
    REFUNDED = "REFUNDED"


class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    RETRYING = "RETRYING"
    CANCELLED = "CANCELLED"
    REFUNDED = "REFUNDED"


class PaymentMethod(str, Enum):
    CARD_SIMULATOR = "CARD_SIMULATOR"
    UPI_SIMULATOR = "UPI_SIMULATOR"
    WALLET_SIMULATOR = "WALLET_SIMULATOR"
    COD_SIMULATOR = "COD_SIMULATOR"
    NETBANKING_SIMULATOR = "NETBANKING_SIMULATOR"


class ShipmentStatus(str, Enum):
    UNASSIGNED = "UNASSIGNED"
    ASSIGNED = "ASSIGNED"
    PICKED_UP = "PICKED_UP"
    IN_TRANSIT = "IN_TRANSIT"
    DELIVERED = "DELIVERED"
    FAILED_DELIVERY = "FAILED_DELIVERY"
    RESCHEDULED = "RESCHEDULED"
    RETURNED_TO_WAREHOUSE = "RETURNED_TO_WAREHOUSE"


class CouponType(str, Enum):
    PERCENTAGE = "PERCENTAGE"
    FIXED_AMOUNT = "FIXED_AMOUNT"
    FREE_SHIPPING = "FREE_SHIPPING"
    CATEGORY_DISCOUNT = "CATEGORY_DISCOUNT"


class ReturnReason(str, Enum):
    DEFECTIVE = "DEFECTIVE"
    WRONG_ITEM = "WRONG_ITEM"
    NOT_AS_DESCRIBED = "NOT_AS_DESCRIBED"
    CHANGED_MIND = "CHANGED_MIND"
    DAMAGED_IN_TRANSIT = "DAMAGED_IN_TRANSIT"


class ReturnStatus(str, Enum):
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PICKUP_SCHEDULED = "PICKUP_SCHEDULED"
    RECEIVED_AT_WAREHOUSE = "RECEIVED_AT_WAREHOUSE"
    INSPECTED_PASSED = "INSPECTED_PASSED"
    INSPECTED_FAILED = "INSPECTED_FAILED"
    REFUNDED = "REFUNDED"


class FraudRiskCategory(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class WarehouseZone(str, Enum):
    RECEIVING = "RECEIVING"
    BULK_STORAGE = "BULK_STORAGE"
    PICKING = "PICKING"
    PACKING = "PACKING"
    DISPATCH = "DISPATCH"
    RETURNS = "RETURNS"


class AuditAction(str, Enum):
    USER_REGISTER = "USER_REGISTER"
    USER_LOGIN = "USER_LOGIN"
    PRODUCT_CREATE = "PRODUCT_CREATE"
    PRODUCT_APPROVE = "PRODUCT_APPROVE"
    ORDER_CREATE = "ORDER_CREATE"
    PAYMENT_SIMULATED = "PAYMENT_SIMULATED"
    SHIPMENT_UPDATE = "SHIPMENT_UPDATE"
    FRAUD_FLAGGED = "FRAUD_FLAGGED"
    REFUND_PROCESSED = "REFUND_PROCESSED"
    STOCK_ADJUSTMENT = "STOCK_ADJUSTMENT"
